# Generated by Django 5.0.2 on 2024-03-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_currency_code_user_gender'),
        ('user', '0010_feedback_service'),
    ]

    operations = [
    ]
